### ISSUE TITLE
CML runner not prolonging its lifetime when job is retriggered

### ISSUE THREAD

**Issue by NikoBele1** [iterative/cml#1008]
Hi, i am having a problem with cml-runner and i am not sure if this is intended behavior or not. My yaml file looks like this:

```
name: test-run
on: 
  workflow_dispatch:
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Deploy runner on GCP
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
        run: |
          cml runner \
              --cloud=gcp \
              --cloud-region=eu-west \
              --cloud-type=e2-medium \
              --labels=cml-runner \
              --reuse \
              --idle-timeout=300
  confirmation:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    timeout-minutes: 120 # 2h
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Give confirmation
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo we are live
```

I start the workflow thorugh Github Website UI and it takes ~6-7 min to execute. When i rerun the workflow it takes ~1 min (because of `--reuse`) and i expect my runner to reset its `--idle-timeout` to 300 again, but the runner terminates after 300 seconds, regardless of how many times i retrigger the workflow. Does the `--reuse` flag maybe interfere with it?
