### ISSUE TITLE
The self-hosted runner: cml-xxx lost communication with the server

### ISSUE THREAD

**Issue by TorRient** [iterative/cml#1053]
### Hi everyone, i have a problem when i using CML to create host runner.

**Log issue:**
The self-hosted runner: cml-xxx lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

**My cml.yaml:**
```
name: CML Report
on:
  push:
    branches:
    - master
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
        run: |
          cml runner \
              --cloud=gcp \
              --cloud-region=us-west \
              --cloud-type=e2-highmem-4 \
              --labels=cml-cpu \
  evaluate:
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-cpu]
    container:
      image: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          dvc repro
          echo "## Metrics" >> report.md
          dvc metrics show --show-md >> report.md
          cml send-comment report.md
```

Any solution?
Thanks all!
