### ISSUE TITLE
support comment `--update` with default `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1105]
CML comment `--update` requires a user-defined PAT. Can we change the implementation to work with the default token too?

Would help a lot with user-friendliness of #1017.

- ref: https://cml.dev/doc/ref/send-comment#github
- discussions:
  + #888
  + https://github.com/iterative/cml.dev/pull/271#discussion_r925462960

**Comment by DavidGOrtega** [comment]
I think that this limitation is a GH issue. `peter-evans/create-or-update-comment` only works with issue comment that are inherently different than commits comments. 
The link of both differs and indeed `peter-evans/create-or-update-comment` have another error when updating commits comments.

In example:
```
https://github.com/DavidGOrtega/fashion_mnist/commit/1ea79b838635928375cf459b978b6e1116cf13cd#commitcomment-79652370
```

```
Run peter-evans/create-or-update-comment@v2
  with:
    comment-id: 7965[2](https://github.com/DavidGOrtega/fashion_mnist/runs/7577465708?check_suite_focus=true#step:3:2)[3](https://github.com/DavidGOrtega/fashion_mnist/runs/7577465708?check_suite_focus=true#step:3:3)70
    body: echo Hi from Action!
  
    token: ***
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Not Found
```

While

```
https://github.com/DavidGOrtega/fashion_mnist/issues/37#issuecomment-1199153152
```
```
Run peter-evans/create-or-update-comment@v2
  with:
    comment-id: 119915315[2](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:2)
    body: echo Hi from Action!
  
    token: ***
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Updated comment id '119915[3](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:3)1[5](https://github.com/DavidGOrtega/fashion_mnist/runs/7577674253?check_suite_focus=true#step:3:5)2'.
```

Want I want to say is that both comments are different in terms of API calls and it does not means anything that the actoin can update issue comments, the question is if thats possible.
Im testing the API via CURL
