### ISSUE TITLE
Plots with multiple curves displayed wrong in cml

### ISSUE THREAD

**Issue by shortcipher3** [iterative/cml#1112]
I am getting beautiful pr curves with DVC, where I have a curve for each class on my plot.

I took what I had and created a cml pipeline and the result looked completely different/worse.

From `dvc` I run:

```
dvc plots diff
```

<img width="344" alt="Screen Shot 2022-07-29 at 3 24 52 PM" src="https://user-images.githubusercontent.com/8680583/182002453-35a0c172-5319-4794-9c29-1d40aca14771.png">

For the `cml` version I run:

```
dvc plots diff --target pr.csv --show-vega origin/main
```

<img width="435" alt="Screen Shot 2022-07-29 at 3 25 31 PM" src="https://user-images.githubusercontent.com/8680583/182002454-0d21eb7d-1615-4f91-84e6-9e86284543d5.png">

For `cml` I used the docker image found on dockerhub, updated five days prior to my usage `dvcorg/cml`

@pared mentioned it might be due to fact that "file" results override flexible plots, as its parsed later, need to prepare a reproduction script.

**Comment by DavidGOrtega** [comment]
👋 @shortcipher3 Could you please give me insights of what CI are you using?

**Comment by DavidGOrtega** [comment]
Would be awesome also if you can provide us the metrics file

**Comment by dacbd** [comment]
I suspect I know what the issue is and have a patch. @shortcipher3 can you try using the setup-cml are or running `npm install -g vega-lite@v5` in your container?

**Comment by shortcipher3** [comment]
For CI I'm using Gitlab, here is the relevant contents of my `.gitlab-ci.yml`

```
# .gitlab-ci.yml
stages:
  - cml_run

cml:
  stage: cml_run
  image: dvcorg/cml:latest
  script:
    # Setup environment
    - ln -sv $(which pip3) /usr/bin/pip3.8
    - pip install -r requirements_fiftyone.txt
    - pip install -r requirements.txt
    - npm install -g vega-lite@v5

    # Additional setup
    - git fetch --prune

    # Write any header information
    - echo "# CML Report" >> report.md

    - dvc fetch reports/model_pr.csv
    - dvc checkout reports/model_pr.csv
    - dvc plots diff 
      --target reports/model_pr.csv --show-vega origin/main > vega.json
    - vl2png vega.json model_pr.png
    - cml publish
      --driver=gitlab
      --rm-watermark
      --md model_pr.png >> report.md

    # Send the report as a comment  
    - cml send-comment report.md
```

My `dvc.yaml` looks like this:
```
plots:
  reports/model_pr.csv:
    template: linear
    x: recall
    y: [precision_class1, precision_class2, precision_class3, precision_class4,
      precision_class5]
    y_label: precision
    title: precision-recall @ iou 0.5
```

@dacbd Adding `npm install -g vega-lite@v5` into my container as seen above didn't help.

@DavidGOrtega I've attached the metrics file.

[model_pr.csv](https://github.com/iterative/cml/files/9234983/model_pr.csv)
