### ISSUE TITLE
cml pr: error: Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by courentin** [iterative/cml#1134]
I use cml (0.17.3) with dvc, at the end of my workflow, I want to commit my dvc.lock with cml pr, but when running `cml pr --skip-ci --merge dvc.lock **/.gitignore` I got an error:
```
error: git checkout -B try-fix-cml 2ba65c1195643b142babccc09fcb9556db44b3f6

        error: Your local changes to the following files would be overwritten by checkout:
        dvc.lock
Please commit your changes or stash them before you switch branches.
Aborting
```

I don't know if I didn't configured cml or my ci correctly but it was working before.
Did I forget something? Is it a bug in cml?

**Comment by 0x2b3bfa0** [comment]
Related to #1126? 🤔

**Comment by dacbd** [comment]
I feel like more context would help?

> Related to #1126? 🤔

Could be.

**Comment by courentin** [comment]
Which information do you need? I can reproduce it quite easily.

It happened even after the first run of `cml pr` on this branch.

Here is a part of my workflow:
```yaml
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Prepares Git repository for CML
        run: cml ci
      - name: Install dependencies
        run: poetry install --no-dev --remove-untracked
      - name: Configure shared cache
        run: |
          poetry run dvc config --local cache.dir /github/home/dvc_cache
          poetry run dvc config --local cache.type symlink
          poetry run dvc config --local cache.shared group

      - name: Pull data
        run: poetry run dvc pull --remote ${{ matrix.aws_region }} || true
      - name: Reproduce pipeline
        run: poetry run dvc repro --pull --glob '*@${{ secrets.LANGUAGE }}'
      - name: Push data
        run: poetry run dvc push --run-cache --remote ${{ matrix.aws_region }}
        if: always()
      - name: Show git status
        run: git status
      - name: Commit dvc state
        run: cml pr --skip-ci --merge "dvc.lock" "**/.gitignore"
```

**Comment by dacbd** [comment]
Maybe I'm slow 🦥 right now. What was the git status output?

**Comment by courentin** [comment]
It was:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dvc.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by dacbd** [comment]
can you make sure that the no "cml created branches" exist already:

my attempt to reproduce this failed to get the same error:
```yml
jobs:
  create-pr:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Standard CML setup
        uses: iterative/setup-cml@v1
        with:
          version: ${{ env.TEST_CML_VERSION || 'latest' }}
      - name: Modifiy file for PR
        run: |
          echo "$(date +%s%N) - pr auto merge" >> cml.log
      - name: CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr --skip-ci --merge .
```
