### ISSUE TITLE
The  report.md(markdown file) File is not appearing in github-actions after pull requests

### ISSUE THREAD

**Issue by AfiqueAye** [iterative/cml#1190]
Hello All, 
I was trying follow the cml.dev documentation on my Github. I have followed all the steps mention there, but I didn't get the expected output. 
I have followed this Documentation:
https://cml.dev/doc/start/github 
Expectation: When I do the Pull Request, I should see a comment from github-actions appear in the Pull Request with My CML report.
Reality: But it was not showing anything. After the pull request, it automatically run the whole command and then I have got the output in the terminal only as a value, no error and no images. seems like the report.md has not published successfully. 
Here is the Cml.yaml code:
```
name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          cat metrics.txt >> report.md
          echo '![](./plot.png)' >> report.md
          cml comment create --publish report.md
```
And Inside the Pull Request, I have only got the output like this:
```
0.864
cml <command>

Commands:
  cml ci                                 Fixes specific CI setups
  cml pr <glob path...>                  Create a pull request with the
                                         specified files
  cml publish <asset>                    Upload an image to build a report
  cml rerun-workflow                     Reruns a workflow given the jobId or
                                         workflow Id
  cml runner                             Launch and register a self-hosted
                                         runner
  cml send-comment <markdown file>       Comment on a commit
  cml send-github-check <markdown file>  Create a check report
  cml tensorboard-dev                    Get a tensorboard link

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --log      Maximum log level
          [string] [choices: "error", "warn", "info", "debug"] [default: "info"]
```
After refreshing the pull request, there was no image, which means the markdown file has not published successfully.Please, anyone knows where is the issue? or anyone has faced the same? kindly, help me.
