### ISSUE TITLE
exp run: fails when used with github actions and CML docker container

### ISSUE THREAD

**Issue by tasdomas** [iterative/cml#1219]

**Comment by pmrowla** [comment]
reopening this and transferring to CML for visibility

**Comment by dacbd** [comment]
minimal example: https://github.com/dacbd/err/blob/main/.github/workflows/dvc-exp-err-cml-container.yml

**Comment by dacbd** [comment]
I'm not sure if this is a p0 / or if this is something fixable on our end. 

It **does not** affect `cml runner` instances because they are running as root already, where most of our examples exist (/purpose) for using the cml container.

We can't chown the directory for users either, I tried a few other things but came up dry...

**Comment by 0x2b3bfa0** [comment]
Running any `cml` command (e.g. `cml ci` to fix the repository configuration) will also disable the `safe.directory` checks on Git, as per #974 & #986.
https://github.com/iterative/cml/blob/c97e5481fb91932dc137da94de0a189d54bdc694/src/cml.js#L118-L120
https://github.com/iterative/cml/blob/c97e5481fb91932dc137da94de0a189d54bdc694/src/cml.js#L83-L116

**Comment by 0x2b3bfa0** [comment]
Not to mention that the official `checkout` action [does the same by default](https://github.com/actions/checkout/blob/8230315d06ad95c617244d2f265d237a1682d445/action.yml#L71-L73) since https://github.com/actions/checkout/pull/762 and https://github.com/actions/checkout/pull/770:

```yaml
  set-safe-directory:
    description: Add repository path as safe.directory for Git global config by running `git config --global --add safe.directory <path>`
    default: true
```
