### ISSUE TITLE
Github (Enterprise) Action that launches a runner on Kubernetes (HP Ezmeral) cluster

### ISSUE THREAD

**Issue by rick-van-veen** [iterative/cml#1261]
Hi I'm trying to achieve the `launch-runner` step from [here](https://cml.dev/doc/self-hosted-runners#allocating-cloud-compute-resources-with-cml) on our kubernetes cluster. After adding steps to install `terraform`, `kubectl` and a `kubectl-plugin` in the action I run the following 
```
cml runner launch --cloud=kubernetes --log=debug --labels-cml
```
and get a pretty long log but I think this is the most relevant part:
```
{"level":"info","message":"2022-11-29T13:40:16.566+0100 [INFO]  provider.terraform-provider-iterative: 2022/11/29 13:40:16 [DEBUG] Received error: &url.Error{Op:\"Get\", URL:\"[https://redacted_url.com:port/apis/batch/v1/namespaces/redacted/jobs/iterative-e0kvt3bw1hba\](https://redacted_url.com:port/apis/batch/v1/namespaces/redacted/jobs/iterative-e0kvt3bw1hba/)", Err:(*errors.errorString)(0xc000990270)}: timestamp=2022-11-29T13:40:16.565+0100"}
{"level":"info","message":"iterative_cml_runner.runner: Creation errored after 4s"}
{"level":"error","message":"terraform error: Error: Failed disposing the machine: Get \"https://redacted_url.com:port/apis/batch/v1/namespaces/redacted/jobs/iterative-e0kvt3bw1hba\": getting credentials: *** executable kubectl failed with exit code 1"}
{"level":"error","message":"terraform error: Error: Failed creating the machine: Failed to create Job! API error: Post \"https://redacted_url.com:port/apis/batch/v1/namespaces/redacted/jobs\": getting credentials: *** executable kubectl failed with exit code 1"}
{"level":"info","message":"2022-11-29T13:40:16.575+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/iterative/iterative/0.11.13/linux_amd[64](https://redacted_url.com/cml-test/cml-tutorial-1/runs/382?check_suite_focus=true#step:10:65)/terraform-provider-iterative pid=95314"}
{"level":"info","message":"2022-11-29T13:40:16.575+0100 [DEBUG] provider: plugin exited"}
```
Any help is appreciated!

**Comment by 0x2b3bfa0** [comment]
Hello, @rick-van-veen! How are you passing the `kubeconfig` file contents to CML?

**Comment by rick-van-veen** [comment]
I currently set `KUBERNETES_CONFIGURATION` to a GitHub secret containing the contents of the config file.

**Comment by 0x2b3bfa0** [comment]
What's the output of running e.g. `mkdir ~/.kube && printenv KUBERNETES_CONFIGURATION > ~/.kube/config && kubectl get pods` instead of `cml runner launch`?

**Comment by rick-van-veen** [comment]
To make the question more complete here is how the full workflow is defined currently:

<details>
<summary>Github actions workflow</summary>

```
name: Launch and Train

on:
  workflow_dispatch:

jobs:
  launch-runner:

    runs-on: [ self-hosted ]
    
    steps:
      # Required for cml
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Setup cml
      - uses: iterative/setup-cml@v1
        with:
          sudo: false
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: hashicorp/setup-terraform@v2
      - uses: azure/setup-kubectl@v3
        env:
          KUBE_CONFIG: ${{ secrets.KUBERNETES_CONFIGURATION }}
      - name: Check kubectl installation
        run: | 
          kubectl config view
      - name: Download and install kubectl plugin
        run: | 
         curl https://bluedata-releases.s3.amazonaws.com/kubectl-epic/3.4/14/linux/kubectl-hpecp.star --output kubectl-hpecp.star
         tar xf kubectl-hpecp.star
         mkdir -p $HOME/.local/bin
         mv kubectl-hpecp $HOME/.local/bin
         echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Check kubectl plugin installation
        run: |
          kubectl plugin list
      - name: Deploy on kubernetes
        env:
          KUBERNETES_CONFIGURATION: ${{ secrets.KUBERNETES_CONFIGURATION }}
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/domain.crt
          TF_LOG_PROVIDER: DEBUG
        run: |
          cml runner launch \
            --cloud=kubernetes \
            --log=debug \
            --labels=cml
```

</details>

As per your request I changed the `cml runner launch` etc. to

```
run: | 
  mkdir ~/.kube && printenv KUBERNETES_CONFIGURATION > ~/.kube/config && kubectl get pods
```

<details>
<summary>Output</summary>


```
Run mkdir -p ~/.kube && printenv KUBERNETES_CONFIGURATION > ~/.kube/config && kubectl get pods
  mkdir -p ~/.kube && printenv KUBERNETES_CONFIGURATION > ~/.kube/config && kubectl get pods
  shell: /usr/bin/bash -e {0}
  env:
    TERRAFORM_CLI_PATH: /home/larry/actions-runner/_work/_temp/e[2](https://redacted_url/cml-test/cml-tutorial-1/runs/399?check_suite_focus=true#step:10:2)a8699[4](https://redacted_url/cml-test/cml-tutorial-1/runs/399?check_suite_focus=true#step:10:4)-8960-4c9a-a680-e0b[5](https://redacted_url/cml-test/cml-tutorial-1/runs/399?check_suite_focus=true#step:10:5)fa11b[6](https://redacted_url/cml-test/cml-tutorial-1/runs/399?check_suite_focus=true#step:10:6)6c
    KUBERNETES_CONFIGURATION: ***
    REPO_TOKEN: ***
    NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/domain.crt
    TF_LOG_PROVIDER: DEBUG
Password for user [myusername]:
Error: inappropriate ioctl for device
Usage:
  kubectl hpecp <command> [<hpecp-fqdn-or-ip-or-url>] [flags]

Examples:

    # To get a new KubeConfig for the current user, if the
    # system is secured by TLS, run the following command
    # and follow all prompts.
    kubectl hpecp refresh <hpecp-fqdn-or-ip-or-url> [flags]

```

</details>

There is more (mostly help to the command kubectl hpecp) to this message and it ends with

`Unable to connect to the server: getting credentials: *** executable kubectl failed with exit code 1`
