### ISSUE TITLE
python 3.7 with cml docker image

### ISSUE THREAD

**Issue by paniabhisek** [iterative/cml#1297]
I am using `iterativeai/cml:0-dvc2-base1` image for our project. Now that comes with `python 3.8` which caused some library conflicts and few errors. Then I could not find another version of `cml` which comes with `python 3.7`. Can you point me to the correct image or any way I can use `python 3.7` with `cml` image ?

**Comment by 0x2b3bfa0** [comment]
Hello, @paniabhisek! Are you using CML with GitHub Actions, or any of the other supported CI/CD systems?

**Comment by paniabhisek** [comment]
@0x2b3bfa0 We use local gitlab server instance. We just take the image from dockerhub and use it.

**Comment by 0x2b3bfa0** [comment]
@paniabhisek, maybe you can use the official `python:3.7` container image and install CML on top, instead of using our images:

```yaml
example:
  image: python:3.7
  variables:
    CML: https://github.com/iterative/cml/releases/latest/download/cml-linux-x64
  script:
    - curl --location $CML --output /bin/cml
    - chmod 755 /bin/cml
    - cml --version
```
