### ISSUE TITLE
Unable to create a report in a gitlab runner with a custom python docker image

### ISSUE THREAD

**Issue by NicoLivesey** [iterative/cml#1392]
Hi I get an error when I try to create a report from a gitlab runner on a custom Docker image.

TO REPRODUCE (in a gitlab ci yaml):
```yaml
image: python:3.9.14-slim-bullseye
script:
  - curl -sL https://deb.nodesource.com/setup_16.x | bash
  - apt-get update && apt-get install -y nodejs
  - npm i -g @dvcorg/cml
  - export REPO_TOKEN=...
  - pip install --no-cache-dir poetry==1.5.0
  - poetry install
  - DOING SOME THINGS
  - cml comment create report.md
```

When the CI triggers I get this error
`{"level":"error","message":"Cannot read properties of null (reading 'split')","stack":"TypeError: Cannot read properties of null (reading 'split')\n    at addSafeDirectory (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:102:7)\n    at fixGitSafeDirectory (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:110:3)\n    at new CML (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:125:5)\n    at setupOpts (/usr/lib/node_modules/@dvcorg/cml/bin/cml.js:72:14)\n    at /usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4778\n    at Array.reduce (<anonymous>)\n    at C (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4576)\n    at _.handleValidationAndGetResult (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:8966)\n    at _.applyMiddlewareAndGetResult (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:9604)\n    at _.runCommand (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:7231)"}`

Already open question:
https://stackoverflow.com/questions/72745070/cml-send-report-is-giving-cannot-read-properties-of-null-reading-split
