### ISSUE TITLE
Resource not accessible by integration Http error.

### ISSUE THREAD

**Issue by Sandy0002** [iterative/cml#1421]
I am new to  CML and trying to learn it so I copied this code and pasted in my cml.yaml file. But it is giving me "Resource not accessible by integration/HTTPError".

```yaml
  name: your-workflow-name
  on: [push]
  jobs:
    run:
      runs-on: ubuntu-latest
      # optionally use a convenient Ubuntu LTS + DVC + CML image
      # container: ghcr.io/iterative/cml:0-dvc2-base1
      steps:
        - uses: actions/checkout@v3
        # may need to setup NodeJS & Python3 on e.g. self-hosted
        # - uses: actions/setup-node@v3
        #   with:
        #     node-version: '16'
        # - uses: actions/setup-python@v4
        #   with:
        #     python-version: '3.x'
        - uses: iterative/setup-cml@v1
        - name: Train model
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt
            python train.py
        - name: Write CML report
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Post reports as comments in GitHub PRs
            cat results.txt >> report.md
            cml comment create report.md
```

What should I do?

**Comment by 0x2b3bfa0** [comment]
Hello, @Sandy0002! Can you please try adding this to your workflow:

```yaml
permissions:
  contents: read
  pull-requests: write
```
