### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by Sandy0002** [iterative/cml#1422]
Invalid URL error is being shown when I am trying to push the program generated images to CML generated reports in my yaml file. I am using following code:

```yaml
name: your-workflow-name
permissions:
  contents: read
  pull-requests: write
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat metrics.txt >> report.md
          echo "## Data viz" >> report.md
          echo "![](./feature_importance.png 'Feature Importance')" >> report.md
          echo "![](./residuals.png 'Residuals')" >> report.md
          cml comment create report.md
```
What should be my next steps?
