### ISSUE TITLE
Token not found error 

### ISSUE THREAD

**Issue by Sandy0002** [iterative/cml#1425]
I am building a cml workflow in that I wrote below code:

```yaml
name: Farmers
on: [push]
jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: cml_run
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro

          # METRICS TRACKING
          # for pulling git history on runner
          git fetch --prune 
          dvc metrics diff main > report.md

          # Add figure to report
          echo "## Validating results by region"
          # cml-publish by_region.png --md >> report.md
          echo '![](./by_region.png "Regional performances")' >> report.md
          cml comment create report.md
```

Now for this code I am getting below error as TOKEN NOT FOUND

```yaml
"level":"error","message":"token not found","stack":"Error: token not found\n    at new Github (/usr/local/lib/node_modules/@dvcorg/cml/src/drivers/github.js:91:23)\n    at CML.getDriver (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:161:35)\n    at CML.commentCreate (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:184:22)\n    at exports.handler (/usr/local/lib/node_modules/@dvcorg/cml/bin/cml/comment/create.js:11:25)\n    at /usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:8993\n    at /usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4949"}
```

How to fix this?
