### ISSUE TITLE
CML runner does not terminate an EC2 used for training on AWS

### ISSUE THREAD

**Issue by GiovanniLeo** [iterative/cml#1471]
Hello I'm using CML with GitLab CI here you can find the definition of the pipeline
```
workflow:
   rules:
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never
launch-runner:
  tags: [cml]
  image: iterativeai/cml:0-dvc2-base1
  timeout: 720h
  script:
    - cml runner launch
      --cloud=aws
      --cloud-region=eu-west-1
      --cloud-type=p3.8xlarge
      --cloud-hdd-size=2048
      --cloud-aws-security-group=sg-**********
      --cloud-aws-subnet=subnet-******
      --reuse-idle
      --labels=cml-gpu
      --log=debug
      --cloud-permission-set=arn:aws:iam::********:instance-profile/cml-ec2-role
train-and-report:
  tags: [cml-gpu]
  needs: [launch-runner]
  image: iterativeai/cml:0-dvc2-base1-gpu
  timeout: 720h
  script:
    - git clone https://github.com/pjreddie/darknet.git
    - cd darknet && sed -i '1s/^/GPU=1\n/' ./Makefile && make
    - cp libdarknet.a /usr/local/lib/ && cp libdarknet.so /usr/local/lib/ 
    - cp darknet /usr/local/bin/ 
    - cp include/darknet.h /usr/local/include/
    - cd ..
    - apt-get update
    - apt-get install libgl1
    - pip install -r requirements.txt
    - dvc checkout --relink --allow-missing
    - dvc pull --allow-missing
    - dvc repro
    - dvc push
    - cml ci
    - git fetch origin
    #- git show origin/master:Net_test_results/map.txt > map-master.txt
    - |
      cat <<EOF > report.md
      # Prado BO
      ## Workspace vs. Master
      | Workspace | Master |
      |:---:|:---:|
      | $(cat map.txt) | $(cat map-master.txt) |
      EOF
    - cml comment create report.md
    - dvc push
    - git add net_OUT/
    - echo $CI_COMMIT_REF_NAME
    - if ! git diff-index --quiet HEAD --; then git commit -m "Update models, test results and info"; fi
    - git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
```

As the documentation said after the job is done the runner should terminate the ec2 but that does not happen, have I done something wrong or is there a problem? Thanks in advance for the support
