### ISSUE TITLE
CML runner RUNNER_PATH parameter with cache

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#170]
User should be able to specify the work dir and could be very useful to be able also the pick it in a "dirty" state. 
This is indeed needed if DVC cache can not help in #161

**Comment by DavidGOrtega** [comment]
We can't setup an easy cache mechanism on GH. However GL and GH allows you to cache things that works for #161 purposes allowing you to cache files or folders using even wildcards

```yaml
jobs:
  train:
    # needs: deploy
    runs-on: [self-hosted,gpu]

    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            report.md
          key: what

      - name: cml_run
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          echo 'Hi from CML' >> report.md
          cml-send-comment report.md
          echo "Trained!"
```

```yaml
stages:
  - ml

train:
  stage: ml
  tags:
    - gpu

  cache:
    paths:
    - report.md
    
  script:
    - echo 'Hi from CML!' >> report.md
    - cml-send-comment report.md
```
