### ISSUE TITLE
cml-py3 doesn't see GPU resources

### ISSUE THREAD

**Issue by pommedeterresautee** [iterative/cml#210]
When I try to run a train task on our AWS own infra the following error is raised on Github actions:
```
...
cfed3d9d6c7f: Pull complete
b5f3fa781593: Pull complete
53448e1579d7: Pull complete
c17eb7b4b5ac: Pull complete
25af3821284d: Pull complete
ea9f7c675b08: Pull complete
6522e7c5ced1: Pull complete
5fb2b6b033bf: Pull complete
1d90b6421d53: Pull complete
5d8a82854f4e: Pull complete
6fa3b0a92e5c: Pull complete
Digest: sha256:2e99adfe066a4383e3d391e5d4f1fbebc37b2c3d8f33ab883e810b35dd771965
Status: Downloaded newer image for dvcorg/cml-py3:latest
dfae88d60614134c3aeb2dc9095356b8cd545e1ad521f7db6575b518fe3ad679
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
About to remove cml1596929922
WARNING: This action will delete both local reference and remote instance.
Successfully removed cml1596929922
```

the workflow looks like this:

```yaml
name: train-model

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [service-catalog, linux, x64]
    container: docker://dvcorg/cml

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_EC2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
        run: |
          echo "Deploying..."
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
          apt-get update && apt-get install -y nvidia-container-toolkit
          RUNNER_LABELS="cml,aws"
          RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
          MACHINE="cml$(date +%s)"
          docker-machine create \
            --driver amazonec2 \
            --amazonec2-instance-type g3s.xlarge \
            --amazonec2-vpc-id vpc-xxxxxxxx \
            --amazonec2-region eu-west-1 \
            --amazonec2-zone "a" \
            --amazonec2-ssh-user ubuntu \
            --amazonec2-ami ami-089cc16f7f08c4457 \
            --amazonec2-root-size 10 \
            $MACHINE
          eval "$(docker-machine env --shell sh $MACHINE)"
          (
          docker-machine ssh $MACHINE "sudo mkdir -p \
            /docker_machine && \
          sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ \
            $MACHINE:/docker_machine && \
          docker run --name runner --gpus all -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e DOCKER_MACHINE=$MACHINE \
            -e repo_token=$repo_token \
            -e RUNNER_LABELS=$RUNNER_LABELS \
            -e RUNNER_REPO=$RUNNER_REPO \
            -e RUNNER_IDLE_TIMEOUT=120 \
            dvcorg/cml-py3:latest && \
          sleep 20 && echo "Deployed $MACHINE"
          ) || (docker-machine rm -y -f $MACHINE && exit 1)
  train:
# ....
```

We run the tests on a self hosted runner.

**Comment by pommedeterresautee** [comment]
I have understood the issue. 
In the config above the AMI for the provisioned machine is a classic Ubuntu AMI instead of the ML dedicated one.
I had to change the AMI ID from the example because the ID from the example is not available in Ireland zone.
And to make Docker able to find GPU you need to have Nvidia drivers on the host plus a dedicated docker tool, etc.

I have found the right version of the ML AMI available in Ireland (the last updated one - version 27 - doesn't work): `ami-062ad6cd7428cb845`

My guess is that AWS has AMI dedicated to each zone.
May be it would make things easier if you your own tested AMI as suggested in https://github.com/iterative/cml/issues/162?

Now the deploy job is able to finish, I see the EC2 machine in the console but... the train tasks crash at the very beginning of the job (no log at all).

![image](https://user-images.githubusercontent.com/1029874/89733114-8fec7300-da53-11ea-9041-e3e41a0c8c0a.png)

![image](https://user-images.githubusercontent.com/1029874/89733140-b01c3200-da53-11ea-92b2-b1b3618f4eea.png)

Do you have an idea of the reason?

**Comment by DavidGOrtega** [comment]
> I have understood the issue.

You are totally right! 

> I have understood the issue.

Without seeing the workflow at least is very difficult. Could you please share it?

**Comment by pommedeterresautee** [comment]
Sure!
It's a a small adaptation from the official example.

```yaml
  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          apt-get update -y
          apt-get -y install python3 python3-venv python3-pip python3-setuptools build-essential git curl ca-certificates python3-dev
          # pip3 install dvc[s3]
          make setup_gpu_dev
          dvc pull resources/XXX
          make train_YYY
          # Report training parameters
          echo "## Training parameter diffs" >> report.md
          echo "```" >> report.md
          cat output/okdoc-pytorch/training_ZZZ.log
          echo "```" >> report.md
          cml-send-comment report.md
```
