### ISSUE TITLE
Proper way to cache dependencies and installing a new library

### ISSUE THREAD

**Issue by sayakpaul** [iterative/cml#229]
Hi. I have been using the container - docker://dvcorg/cml-py3:latest. 

I am looking for the following solutions:
- A proper way to cache the Python dependencies. Currently, I am doing something like - 
    ```yaml
    - uses: actions/cache@master
        id: cache
        with:
          path: ${{ env.pythonLocation}}/lib/python3.7/site-packages/*
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt
    ```
   But it results in - 
    ```
   WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    ```
- I am trying to install `wandb` for easy experiment tracking of ML models. But it results in errors Full error log is available [here](https://github.com/sayakpaul/wine/runs/1042487949?check_suite_focus=true) (see **Install Dependencies**).

All the code is available at [this branch](https://github.com/sayakpaul/wine/tree/experiment-1).

**Comment by sayakpaul** [comment]
I updated the path to `path: ~/.cache/pip` as well but still no luck.

**Comment by DavidGOrtega** [comment]
In the meantime we review it

### Solution 1
Would be extending our docker image a possibility? You would need a docker hub account to store your image.

```docker
FROM dvcorg/cml

RUN ...
```
then docker build and publish in your hub.

### Solution 2
Another solution could be use ```dvcorg/cml``` and use ```setup-python``` and ```cache``` action.

**Comment by DavidGOrtega** [comment]
@sayakpaul did it work? 😃

**Comment by sayakpaul** [comment]
Sorry @DavidGOrtega for the delay. Solution 2 seems like more feasible option to me. Could expand on that a bit?

**Comment by DavidGOrtega** [comment]
@sayakpaul sure!  The idea would be using ```iterative/cml``` instead and installing python through an action

```yaml
name: Metric logging with wandb

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
            
      - uses: actions/cache@master
        id: cache
        with:
          path: ${{ env.pythonLocation}}/lib/python3.7/site-packages/*
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt
     
      - name: show module
        run: pip show pandas
      
      - name: Train model and log wandb metric
        run: |
          # Your ML workflow goes here
          python train.py --key ${{ secrets.WANDB_API_KEY }}
          echo "Finished run."
          cat metrics.txt >> report.md
          cml-send-comment report.md

      - name: Archive metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics csv file
          path: metrics.csv
```
