### ISSUE TITLE
cml-cloud-runner now depends on cloning the repo

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#328]
This only happens in GH, if the checkout action is not used we wont have the repo so its not possible to guess the repo.

**Comment by DavidGOrtega** [comment]
I think it's ok. The issue right now is that the deploy job should have to setup the checkout action first in order to get the repo or setup the ```repo``` parameter explicitly. So its perfectly acceptable.

```yaml
deploy-tf:
    runs-on: [ubuntu-latest]
    container: docker://iterative/cml:latest

    steps:
      - uses: actions/checkout@v2
      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.REPO_TOKEN }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo "Deploying..."
          
          test-cml-cloud-runner \
          --labels=tf \
          --type=t2.micro \
          --region us-west \
          --idle-timeout=120
``` 

```yaml
deploy-tf:
    runs-on: [ubuntu-latest]
    container: docker://iterative/cml:latest

    steps:
      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.REPO_TOKEN }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo "Deploying..."
          
          test-cml-cloud-runner \
          --labels=tf \
          --type=t2.micro \
          --region us-west \
          --idle-timeout=120 \
          --repo=https://github.com/${GITHUB_REPOSITORY}
```
