### ISSUE TITLE
docs: make GHA default, docker optional

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#482]
See e.g. https://partner.github.com/integration-resources/2020/11/24/pattern-setting-up-a-cli-on-github-s-hosted-runners.html

Would make it super easy to set up:

```yaml
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/cml@v1
      - name: 'Train my model'
        ...
        cml-send-comment report.md
```

EDIT:

```yaml
- uses: actions/setup-node@v1
- uses: iterative/setup-cml@v1
```
works well but needs better documentation. Any objections to making it more prominent than `container: docker://`? Would fix e.g. #360
