### ISSUE TITLE
How should I access logs and images from within the container

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#605]
coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/855531781179965471)

> When I am running with my own container, how should I access logs and images from within the container?
Do I need to mount a volume within the container in order for the runner to see that? I am running with the following:

```yaml
model-training:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: 
      image: docker://spr3n/torch:latest
      options: --gpus all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }} 
        run: |
          # DVC stuff
          git fetch --prune
          dvc init
          dvc repro
          /opt/conda/bin/python examples/synthetic_s3.py
          
          echo "# 3D Convolutional Net" >> report.md
          # Does not see images saved by `examples/synthetic_s3.py`
          echo $(ls ./examples) 
          cml-publish examples/loss.png --md >> report.md
          cml-send-comment report.md 
```
