### ISSUE TITLE
NVIDIA drivers don't exist

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/cml#611]
I'm running into the following error when running a CML workload which requires a GPU

```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
ERROR: failed to reproduce 'dvc.yaml': failed to run: rvl train bert-seq-classifier data/processed/train_er4_data.jsonl models/bert-seq-classifier.pkl, exited with 1
```

I'm use the GPU image and an instance with a GPU from aws. Perhaps I've misunderstood, and the docker containers are not ready to roll with GPU support?

My cml.yaml is:

```
name: Run DVC repro
on: [push]
jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region eu-west \
          --cloud-type=g4dn.xlarge \
          --cloud-spot true \
          --labels=cml-runner,reviews-labeler \
          --idle-timeout 60
  run:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: cml_run
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Install dependencies
          pip install -r requirements.txt
          pip install .

          dvc repro

          # Report metrics
          echo "## Metrics" > report.md
          git fetch --prune

          dvc metrics diff main --show-md | grep "Change\|\-\-\-" >> report.md
          dvc metrics diff main --show-md | grep -v "threshold-" | grep "weighted" | sort >> report.md
          sed "s/results\///g" -i report.md

          cml-send-comment report.md
 
          dvc push          

      - uses: EndBug/add-and-commit@v7
        with:
           add: 'dvc.lock --force'
           pull_strategy: 'NO-PULL'
           message: 'chg: dvc repro'

**Comment by 0x2b3bfa0** [comment]
Can you please try to run the workflow below and post the logs?

```yaml
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: >-
          cml-runner
          --labels=test 
          --cloud=aws
          --cloud-region=eu-west
          --cloud-type=g4dn.xlarge
          --cloud-spot
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
run:
    needs: deploy
    runs-on:
      - self-hosted
      - test
    steps:
      - run: nvidia-smi
```

**Comment by 0x2b3bfa0** [comment]
@ivyleavedtoadflax, it looks like you forgot to expose the GPU in the container:

```yaml
container:
  image: docker://dvcorg/cml:0-dvc2-base1-gpu
  options: --gpus all
```
