### ISSUE TITLE
nvidia smi not accesible in CML AMI

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#666]
We are deploying a runner and the test within a container and without should be working...
Right now the CML image does not. Why? I do not remember a fundamental change here 🤔 

https://gitlab.com/iterative.ai/cml/-/jobs/1444164845
```sh
$ nvidia-smi
/usr/bin/bash: line 138: nvidia-smi: command not found
Cleaning up file based variables
```

Complete pipeline https://gitlab.com/iterative.ai/cml/-/pipelines/341171784

## gitlab ci

```yaml
stages:
  - deploy
  - test

deploy_job:
  stage: deploy
  when: always
  image: dvcorg/cml:0-dvc2-base1-gpu
  script:
    - cml-runner --cloud aws --cloud-region us-west --cloud-type g2.2xlarge
      --cloud-spot --labels=cml-runner-gpu

test_runner:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  script:
    - sudo pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi

test_container:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  image: dvcorg/cml:0-dvc2-base1-gpu
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
```
