### ISSUE TITLE
--gpus option not working on recently updated docker image

### ISSUE THREAD

**Issue by sergeychuvakin** [iterative/cml#698]
I have the following YAML workflow: 
```yaml
on:
  push:
    branches:
      - GPU-debug

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        run: |
          cml-runner \
              --repo https://github.com/sergeychuvakin/DVC_CML_sanbox \
              --token=$PERSONAL_ACCESS_TOKEN \
              --cloud aws \
              --cloud-region us-west-1 \
              --cloud-type=g3.4xlarge \
              --labels=cml-runner \
              --idle-timeout 30
    
  model-training:
    timeout-minutes: 5000
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://dvcorg/cml:0-dvc2-base0-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Train model
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          nvidia-smi
        shell: bash
```
I face the following error, while image building:

<img width="998" alt="Screenshot 2021-08-17 at 17 47 12" src="https://user-images.githubusercontent.com/33733128/129748048-959d8a5d-5b0e-4f60-aff0-f9774dff3617.png">

Namely I tried different images:
`docker://dvcorg/cml:0-dvc2-base0-gpu` or 
`docker://dvcorg/cml:0-dvc2-base1-gpu`
 gave me the same error

When i disabled options `--gpus all` - this error was  resolved but at the same time `nvidia-smi` was not found 

<img width="1027" alt="Screenshot 2021-08-17 at 17 50 38" src="https://user-images.githubusercontent.com/33733128/129748640-29febb84-0c1b-4752-a9d6-0a9c5ab41f51.png">

Thanks in advance!

**Comment by sergeychuvakin** [comment]
logs attached
[logs_73.zip](https://github.com/iterative/cml/files/7000984/logs_73.zip)

**Comment by 0x2b3bfa0** [comment]
## Minimal example

```yaml
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: >-
          cml-runner
          --cloud=aws
          --cloud-region=us-west-1
          --cloud-type=g3.4xlarge
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  train:
    needs: deploy
    runs-on: self-hosted
    container:
      image: docker://iterativeai/cml:0-dvc2-base0-gpu
      options: --gpus all
    steps:
      - run: nvidia-smi
```
