### ISSUE TITLE
cml-runner self-hosted issues

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#721]
- `~/.cml/cml-*/` is not cleaned up
- `~/.cml/cml-*/` is not named according to `--name`
- feature request: local secrets (`cml runner --env` flag similar to `docker run --env`)

**Comment by 0x2b3bfa0** [comment]
Variables stored in the GitHub Actions self–hosted runner `.env` file will update the existing ones, and not replace them, as you can see in [actions/runner@f259e57 → src/Runner.Listener/Program.cs:152](https://github.com/actions/runner/blob/f259e5706fd354b1bf6b54ea0a8705a5eaff48bf/src/Runner.Listener/Program.cs#L152).

We can use [`env(1)`](https://man7.org/linux/man-pages/man1/env.1.html) or the [`env`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) option on Node JS' [`child_process`](https://nodejs.org/api/child_process.html) functions to reset the environment and avoid the propagation of variables other than the ones in the `.env` file.

#### Shell

```bash
env --ignore-environment ./run.sh
```

#### Node JS

It would suffice to filter out the environment on [`utils.js`](https://github.com/iterative/cml/blob/2e9a21ddb4b4eb1261a75ba72f89b98b1972d063/src/utils.js#L13) so it doesn't propagate to the child process.
https://github.com/iterative/cml/blob/2e9a21ddb4b4eb1261a75ba72f89b98b1972d063/src/utils.js#L13

https://github.com/iterative/cml/blob/2e9a21ddb4b4eb1261a75ba72f89b98b1972d063/src/drivers/github.js#L227-L237

**Comment by DavidGOrtega** [comment]
> feature request: local secrets (cml runner --env flag similar to docker run --env)

Why do we exactly want this feature @casperdcl ?

**Comment by 0x2b3bfa0** [comment]
https://iterativeai.slack.com/archives/C01900GSB4J/p1632232145260800?thread_ts=1632223956.257700&cid=C01900GSB4J

**Comment by casperdcl** [comment]
just realised this is also a problem on all runners (not just manual self-hosted)

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: iterative/setup-cml@v1
    - uses: actions/checkout@v2
    - run: |
        cml runner --labels=cml-runner --cloud=aws --cloud-type=t2.micro
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REPO_TOKEN: ${{ secrets.CML_CI_TOKEN }}
  train:
    runs-on: [self-hosted, cml-runner]
    steps:
    - run: env # why does this list AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY ??
```

should really either

- whitelist-only vanilla CI vars (`GITHUB_ENV` etc) or
- at least blacklist CML config vars (`AWS_*ACCESS_KEY` etc)
