### ISSUE TITLE
Python Action not supported

### ISSUE THREAD

**Issue by elleobrien** [iterative/cml#81]
I see in the README example how to install Python "manually", but there's a GH action `setup-python` already built for installing Python [that seems recommended](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions). 

I was trying this out with the cml docker container, and there seems to be an odd interaction between the docker container and `setup-python`.

For example, if I'm not using our docker container and run this workflow:
```yaml
name: your-workflow-name

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/dvc-cml:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install sklearn

```

Everything runs beautifully. As soon as I add `container: docker://dvcorg/dvc-cml:latest` to the .yaml file, though, I hit the following error:

![image](https://user-images.githubusercontent.com/29716724/80842455-77e49800-8bb6-11ea-8451-7ea804c32dfb.png)

Any ideas?

**Comment by jbencook** [comment]
I got this working with the `dvcorg/cml:latest` image. By default, the container service mounts `/opt/hostedtoolcache` to `/__t` in the container, but that breaks the Python installs which are compiled to live in `/opt/hostedtoolcache` specifically.

But the container syntax lets you add mounted volumes. Here's a workflow file that worked for me:

```
name: test-setup-python

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container:
      image: docker://dvcorg/cml:latest
      volumes:
        - /opt/hostedtoolcache:/opt/hostedtoolcache

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install sklearn
```

It also works with `setup-python@v2` and it works on a self-hosted runner. I'm pretty sure the base image will need to be Ubuntu 18.04, but it looks like all your images are so that wouldn't be a problem.

IMO this is better than shipping with your own Python because matrix testing works and it would make CML workflows more similar to other GitHub Actions setups. I'm happy to help with PRs to update examples if you think this is useful.
