### ISSUE TITLE
Using py3 container

### ISSUE THREAD

**Issue by elleobrien** [iterative/cml#82]
I'm trying to use the py3 docker container so that I don't have to manually install python on my GitHub hosted runner. I'm not sure I'm doing this correctly. My .yaml file says:

```yaml
 
name: train-my-model
on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/dvc-cml-py3:latest

    steps:
      - uses: actions/checkout@v2
      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          update-alternatives --install /usr/bin/pip pip $(which pip3) 10
          test -f requirements.txt && pip3 install -r requirements.txt
          python train.py
          echo "# CML report" >> report.md
          cat metrics.json >> report.md
          cat ![](confusion_matrix.png) >> report.md
          cml-send-comment report.md
```

And I'm getting an error trying to install the required packages [in my repo](https://github.com/andronovhopf/cml_base_case)
![Screen Shot 2020-05-05 at 2 19 59 PM](https://user-images.githubusercontent.com/29716724/81117208-8fd05a80-8edb-11ea-856f-a0d01d994b00.png)

I'm sure I'm just doing something wrong in my cml.yaml file; could you point me to the right way to setup Python & pip?
