### ISSUE TITLE
Error deploying AWS EC2 runner in Gitlab

### ISSUE THREAD

**Issue by gitdoluquita** [iterative/cml#826]
Hey everyone,
I am not being able to use the cml runner in my gitlab CI pipeline.

I forked the repo: https://gitlab.com/iterative.ai/cml-cloud-case for a quick test before setting the pipeline in my actual project.

I setted the CI/CD variables needed:
![image](https://user-images.githubusercontent.com/15278119/144440068-2be36a75-a96a-42ee-aa4c-4803566ae8b2.png)
I setted both repo_token and  REPO_TOKEN because it says lower case in Gitlab's repo README and upper case in [CML Documentation](https://cml.dev/doc/usage?tab=GitLab).

And I am getting this error:
[job.log](https://github.com/iterative/cml/files/7642671/job.log)
For me it looks like the job is not getting a "heartbeat" from the runner deployed.

I tried some different machines but right now my gitlab-ci.yml is like this:
```yml
stages:
  - deploy
  - train

deploy_job:
  stage: deploy
  when: always
  image: dvcorg/cml
  script:
    - cml-runner
      --cloud aws
      --cloud-region us-east
      --cloud-type t2.micro
      --cloud-hdd-size 64
      --labels=cml-runner-gpu

train_job:
  stage: train
  when: on_success
  image: dvcorg/cml-py3
  tags:
    - cml-runner-gpu

  script:
    - apt-get update -y
    - apt-get install python3-dev -y
    - pip install -r requirements.txt
    - cat gpu_info.txt >> report.md
    
    - cml-send-comment report.md 
```

One weird thing is that the machine is being created, but the job is falling.
![image](https://user-images.githubusercontent.com/15278119/144441985-fd3915ff-4a77-4568-b15b-8de1cb5944c7.png)

If I could provide any other relevant information please let me know!

Thank you all in advance!

**Comment by DavidGOrtega** [comment]
👋 @gitdoluquita. Yesterday Gitlab had a hiccup, thats maybe the reason?

I would check:
 - why do you have `REPO_TOKEN` and `repo_token`? One of them would suffice and indeed `repo_token` will have priority over the other.
 - Check the list of runners to see if you can see the runner being deployed

Additionally change the images. Is not related to your case probably but in any case its outdated:

```yaml
deploy_job:
  image: iterativeai/cml:0-dvc2-base1

job:
  image: iterativeai/cml:0-dvc2-base1-gpu
```
