### ISSUE TITLE
difficult to set `--cloud-ssh-private`

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#852]
As per https://github.com/iterative/cml/issues/848#issuecomment-996761575, there's an issue with `--cloud-ssh-private=--...`.

* Caused by yargs/yargs-parser#433

**Comment by DavidGOrtega** [comment]
I use it `cloud-ssh-private` and works.
A better issue title might "`--cloud-ssh-private` is difficult to set"?

**Comment by dacbd** [comment]
What are your thoughts on something to populate an authorized key for you? `--public-key=` akin to adding something like:
```
echo "ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBDYd3ssa6L15jQC5bckJ2viWlA1tBygxeWoy3s0S14ZHMxUMfp7u2yqficpHO5b+pjgg7Lz+80Ibw157waTZPM+xbF2/KGqS7aYV0L/R8VbWjVEpzxZEeoxSCwFA1tHWUg==" >> /home/ubuntu/.ssh/authorized_keys
```
in a startup script?
I feel like it might be creeping on the feature too much unless people don't care about a ton of cli args.

Maybe document common debugging options/steps somewhere like the above, `TF_LOG` env, `journalctl -u cml.service` etc

**Comment by casperdcl** [comment]
> document common debugging options/steps somewhere

:100: - feel free to create a new page on the [wiki](https://github.com/iterative/cml/wiki)

**Comment by 0x2b3bfa0** [comment]
Doesn't the SSH documentation work as expected?
https://cml.dev/doc/ref/runner#using---cloud-ssh-private

**Comment by 0x2b3bfa0** [comment]
Publishing some old snippets I wrote months ago:

## Terraform with `cml runner`

The following code snippets produce a full trace-level log of the Terraform provider, useful to diagnose a lot of hard to reproduce bugs related to `cml-runner --cloud` and cloud instances.

### GitLab — `.gitlab-ci.yml`

```yaml
debug:
  when: always
  image: iterativeai/cml
  variables:
    TF_LOG: trace
    TF_LOG_PATH: /tmp/terraform.log
  script:
    - cml-runner
      --cloud aws
      --cloud-region us-west
      --cloud-type t2.micro
      --labels=cml-runner
      || true
    - cat "$TF_LOG_PATH"
```

### GitHub — `.github/workflows/debug.yml`

```yaml
on: workflow_dispatch
env:
	TF_LOG: trace
  TF_LOG_PATH: /tmp/terraform.log
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - run: >-
          cml-runner
		      --cloud aws
		      --cloud-region us-west
		      --cloud-type t2.micro
		      --labels=cml-runner
					|| true
			- run: >-
          cat "$TF_LOG_PATH"
```

## Debugging GitLab CI/CD with tmate


```yaml
debug:
  when: always
  script:
    - mkdir -p ~/.ssh && printf 'y\n\n' | ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa    
    - apt update && apt install --yes tmate expect    
    - TERM=xterm unbuffer ./tmate -FS /tmp/tmate.sock | cat
```

## Using cml-runner with --cloud-ssh-private

```
cml runner ··· --cloud-ssh-private="$(cat ~/.ssh/id_rsa)"
```

You can get the instance address by setting the `TF_LOG` and `TF_LOG_PATH` environment variables and searching for *instance address* in the logs.

## Debugging cml-runner --cloud=aws
```
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: >-
          cml-runner
          --labels=test
          --cloud=aws
          --cloud-region=eu-west
          --cloud-type=g4dn.xlarge
          --cloud-spot
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
run:
    needs: deploy
    runs-on:
      - self-hosted
      - test
    steps:
      - run: |
          set -x
          cat /var/log/cloud-init.log || true
          cat /var/log/cloud-init-output.log || true
          nvidia-smi || true
```
