### ISSUE TITLE
runner: support GCP OIDC auth

### ISSUE THREAD

**Issue by rodrigoalmeida94** [iterative/cml#862]
I'm attempting to create a CML template workflow to use a self-hosted runner in GCP. To authenticate into GCP I would like to use the newly available OIDC method (described [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)).

After using the [google-github-actions/auth](https://github.com/google-github-actions/auth) a authentication file is created, but when I run the `cml runner` command I get the following traceback:
```bash
{"level":"warn","message":"ignoring RUNNER_NAME environment variable, use CML_RUNNER_NAME or --name instead"}
{"level":"info","message":"Preparing workdir /home/runner/.cml/cml-8cqnfumhcx..."}
{"level":"info","message":"Deploying cloud runner plan..."}
{"level":"info","message":"Terraform apply..."}
{"level":"error","message":"terraform -chdir='/home/runner/.cml/cml-8cqnfumhcx' apply -auto-approve\n\t\nTerraform used the selected providers to generate the following execution\nplan. Resource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n  # iterative_cml_runner.runner will be created\n  + resource \"iterative_cml_runner\" \"runner\" {\n      + cloud                = \"gcp\"\n      + driver               = \"github\"\n      + id                   = (known after apply)\n      + idle_timeout         = 300\n      + image                = (known after apply)\n      + instance_hdd_size    = 35\n      + instance_ip          = (known after apply)\n      + instance_launch_time = (known after apply)\n      + instance_type        = \"m+k80\"\n      + labels               = \"cml-gpu\"\n      + name                 = \"cml-8cqnfumhcx\"\n      + region               = \"us-west\"\n      + repo                 = \"https://github.com/developmentseed/ml-project-seed\"\n      + single               = false\n      + spot                 = false\n      + spot_price           = -1\n      + ssh_public           = (known after apply)\n      + token                = (sensitive value)\n    }\n\nPlan: 1 to add, 0 to change, 0 to destroy.\niterative_cml_runner.runner: Creating...\n\n\t╷\n│ Error: Failed disposing the machine: Couldn't extract the project identifier from the given credentials!\n│ \n│   with iterative_cml_runner.runner,\n│   on main.tf line 14, in resource \"iterative_cml_runner\" \"runner\":\n│   14: resource \"iterative_cml_runner\" \"runner\" {\n│ \n╵\n╷\n│ Error: Failed creating the machine: Couldn't extract the project identifier from the given credentials!\n│ \n│   with iterative_cml_runner.runner,\n│   on main.tf line 14, in resource \"iterative_cml_runner\" \"runner\":\n│   14: resource \"iterative_cml_runner\" \"runner\" {\n│ \n╵\n","stack":"Error: terraform -chdir='/home/runner/.cml/cml-8cqnfumhcx' apply -auto-approve\n\t\nTerraform used the selected providers to generate the following execution\nplan. Resource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n  # iterative_cml_runner.runner will be created\n  + resource \"iterative_cml_runner\" \"runner\" {\n      + cloud                = \"gcp\"\n      + driver               = \"github\"\n      + id                   = (known after apply)\n      + idle_timeout         = 300\n      + image                = (known after apply)\n      + instance_hdd_size    = 35\n      + instance_ip          = (known after apply)\n      + instance_launch_time = (known after apply)\n      + instance_type        = \"m+k80\"\n      + labels               = \"cml-gpu\"\n      + name                 = \"cml-8cqnfumhcx\"\n      + region               = \"us-west\"\n      + repo                 = \"https://github.com/developmentseed/ml-project-seed\"\n      + single               = false\n      + spot                 = false\n      + spot_price           = -1\n      + ssh_public           = (known after apply)\n      + token                = (sensitive value)\n    }\n\nPlan: 1 to add, 0 to change, 0 to destroy.\niterative_cml_runner.runner: Creating...\n\n\t╷\n│ Error: Failed disposing the machine: Couldn't extract the project identifier from the given credentials!\n│ \n│   with iterative_cml_runner.runner,\n│   on main.tf line 14, in resource \"iterative_cml_runner\" \"runner\":\n│   14: resource \"iterative_cml_runner\" \"runner\" {\n│ \n╵\n╷\n│ Error: Failed creating the machine: Couldn't extract the project identifier from the given credentials!\n│ \n│   with iterative_cml_runner.runner,\n│   on main.tf line 14, in resource \"iterative_cml_runner\" \"runner\":\n│   14: resource \"iterative_cml_runner\" \"runner\" {\n│ \n╵\n\n    at /usr/local/lib/node_modules/@dvcorg/cml/src/utils.js:21:27\n    at ChildProcess.exithandler (node:child_process:404:5)\n    at ChildProcess.emit (node:events:390:28)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)","status":"terminated"}
```

Looking through the [terraform documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials), they state:
```
Note: Currently the only supported service account credentials are credentials downloaded from Cloud Console or generated by gcloud.
```
This could be the reason why this OIDC generated authentication file is not accepted, but I'm not sure.

Have you encountered this issue before? Did you experiment with OIDC for GCP? Any help would be greatly appreciated.

https://github.com/developmentseed/ml-project-seed/pull/6

For reference here is the current state of my github actions workflow:
```
name: CML (GCP)
on: [push]
permissions:
  id-token: write
  contents: read

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
            workload_identity_provider: 'projects/348645304830/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'my-service-account@bp-padang.iam.gserviceaccount.com'
            project_id: 348645304830
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          gcloud services list 
          cml runner \
              --cloud=gcp \
              --cloud-region=us-west \
              --cloud-type=m+k80 \
              --labels=cml-gpu
```

**Comment by dacbd** [comment]
I'm not sure, I don't think this auth method has been tested much. It is expecting GCP JSON credentials that have the following
```json
{
  "type": "",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}
```
you could check to see what is different with the generated creds? from the error it looks like the project_id wasn't present?

**Comment by rodrigoalmeida94** [comment]
I checked what the credentials look like and they have the following configuration:
```
{
   "type":"external_account",
   "audience":"",
   "subject_token_type":"urn:ietf:params:oauth:token-type:jwt",
   "token_url":"https://sts.googleapis.com/v1/token",
   "service_account_impersonation_url":"",
   "credential_source":{
      "url":"",
      "headers":{
         "Authorization":"***"
      },
      "format":{
         "type":"json",
         "subject_token_field_name":"value"
      }
```
This is clearly quite different, but I seem to be able to run `gcloud` commands with this. Could it be that the terraform GCP `provider` config is setup in such a way that this credentials can't be used? ([reference](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#example-usage---basic-provider-blocks))

**Comment by rodrigoalmeida94** [comment]
Gotcha, thanks a lot @dacbd ! 

For now I'll be using the service account credential method that you described in your docs, since I believe any other solution to get around this terraform limitation would most likely be very messy. Thanks for you support in any case!

I'll keep an eye on this issue!

**Comment by dacbd** [comment]
@rodrigoalmeida94 we will probably want to keep an eye out on this line as well: https://github.com/google-github-actions/auth#authenticating-via-workload-identity-federation

**Comment by dacbd** [comment]
Going to be taking a deeper look at this soonᵀᴹ

**Comment by dacbd** [comment]
@rodrigoalmeida94 this is supported by the new TPI release: https://github.com/iterative/terraform-provider-iterative/releases/tag/v0.10.8
I am currently slowly working on https://github.com/iterative/cml.dev/pull/208 to document some of the gotchas.

I think that it's safe to this is not the currently recommended mode of authentication for using `cml runner` as if your workflow (with no changes to the default authentication resource) lasts longer than 1hr the credentials used by `cml runner` will expire and the instance self-termination will fail.

I intend to also document/create an easy/convenient method to update the credentials in use.
You can follow updates here: https://github.com/iterative/cml/issues/987

### Basic example:
```yml
#...
      - uses: actions/checkout@v3
        with:
          path: main
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/200200923017/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-actions'
          service_account: 'cml-runner@cml-pulse.iam.gserviceaccount.com'
      - run: |
          cml runner \
            --single \
            --labels=test-oidc \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2 \
#...
```
