### ISSUE TITLE
Broken on Windows because of SNYK-JS-COLORS-2331906

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#863]
Caused by our direct dependency on `winston`

* Tracked upstream on https://github.com/winstonjs/winston/issues/2007
* Caused by https://github.com/Marak/colors.js/issues/285

#### See also
* [Snyk](https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what)
* [Bleeping Computer](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps)
* [The Verge](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected)

**Comment by 0x2b3bfa0** [comment]
#### Minimal working example

```yaml
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@v2
    - run: npm install winston@3.3.3
    - run: node -e "require('winston')"
```
