### ISSUE TITLE
`send-comment` PR for commit sha \"HEAD\" not found

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#880]
If I repeat the same workflow where the PR was done by `cml pr` `send-comment` seems to not found the PR for the given commit sha

```sh
{"level":"error","message":"PR for commit sha \"HEAD\" not found","stack":"Error: PR for commit sha \"HEAD\" not found\n    at CML.commentCreate (/usr/local/lib/node_modules/@dvcorg/cml/src/cml.js:148:15)\n    at async Object.exports.handler (/usr/local/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:13:15)"}
```

**Comment by judahrand** [comment]
I'm running into the same thing with Github.

`cml send-comment --update` works in a workflow triggered by a PR but `cml send-comment --pr --update` does not.

**Comment by hlkcrcck** [comment]
Any updates or workarounds for that issue? It is not possible to send comments to the PR right now on Github

**Comment by 0x2b3bfa0** [comment]
```yaml
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log
      - run: git fetch --unshallow
      - run: git log -2
      - run: echo $GITHUB_SHA
      - run: gh api /repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls
```
