### ISSUE TITLE
runner --driver=github Docker-in-Docker

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#908]
Docker-in-Docker (probably) doesn't work with GitHub?

(P.S. we recommend `--docker-volumes=/var/run/docker.sock:/var/run/docker.sock` for GitLab)

```yml
jobs:
  deploy:
    steps:
    - run: cml runner --cloud=aws --labels=cml-aws
  train:
    needs: deploy
    container: docker://<some_container>
    steps:
    - uses: [self-hosted, cml-aws]
    - run: docker run ...
```

Have we tried using `docker:dind` for `<some_container>`?

**Comment by 0x2b3bfa0** [comment]
## Working

It seems like GitHub takes care of mounting any volumes it needs for running `docker` commands in `container` jobs.

### `container: docker:dind`

```yaml
on: workflow_dispatch     
jobs:
  example:
    runs-on: ubuntu-latest
    container: docker:dind
    steps:
    - run: echo FROM python > Dockerfile
    - run: docker build .
```

### `container: docker`

```yaml
on: workflow_dispatch     
jobs:
  example:
    runs-on: ubuntu-latest
    container: docker
    steps:
    - run: echo FROM python > Dockerfile
    - run: docker build .
```

### `container: alpine` + `apk add docker`

```yaml
on: workflow_dispatch     
jobs:
  example:
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - run: apk add docker
    - run: echo FROM python > Dockerfile
    - run: docker build .
```

### `container: null`

```yaml
on: workflow_dispatch     
jobs:
  example:
    runs-on: ubuntu-latest
    container: null
    steps:
    - run: echo FROM python > Dockerfile
    - run: docker build .
```

### Not Working

When a self–hosted runner is being executed inside a container, users can't use it with container steps nor container actions.

```yaml
on: workflow_dispatch     
jobs:
  example:
    runs-on: self-hosted # containerized runner
    container: alpine
    steps:
    - run: apk add docker
    - run: echo FROM python > Dockerfile
    - run: docker build .
```

```
Error: Container feature is not supported when runner is already running inside container.
```

* https://github.com/actions/runner/issues/367
* https://github.com/actions/runner/issues/406
