### ISSUE TITLE
`cml ci` before `cml pr` breaks a Github workflow

### ISSUE THREAD

**Issue by nukelash** [iterative/cml#909]
For example,
```
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - run: date > file
    - run: cml ci && cml pr file
      env:
        GITHUB_TOKEN: ${{ github.token }}
```
Results in:
```
{"level":"error","message":"\n    git config --unset http.https://github.com/.extraheader && \\\n    git config user.name \"Olivaw[bot]\" && \\\n    git config user.email \"olivaw@iterative.ai\" && \\\n    git remote set-url origin \"***github.com/dacbd/err.git\"\n\t\n\t","stack":"Error: \n    git config --unset http.https://github.com/.extraheader && \\\n    git config user.name \"Olivaw[bot]\" && \\\n    git config user.email \"olivaw@iterative.ai\" && \\\n    git remote set-url origin \"***github.com/dacbd/err.git\"\n\t\n\t\n    at /usr/local/lib/node_modules/@dvcorg/cml/src/utils.js:20:27\n    at ChildProcess.exithandler (node:child_process:406:5)\n    at ChildProcess.emit (node:events:520:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)"}
Error: Process completed with exit code 1.
```
See: https://github.com/dacbd/err/runs/5518152152?check_suite_focus=true
