### ISSUE TITLE
`cml <sub-cmd>` on cml runner instance fails

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#920]
I have tried a few iterations of this:
```yml
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: deploy runner
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          cml runner \
            --single \
            --labels=test \
            --token=${{ secrets.DACBD_PAT }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-highcpu-2
  test:
    needs: [setup]
    runs-on: [self-hosted, test]
    steps:           
      - uses: actions/checkout@v2
      - run: |
          which cml
          cml ci
```
[Fails](https://github.com/dacbd/cml-pulse/runs/5607653370?check_suite_focus=true) with an odd message: `Error: Cannot find module '/tmp/tmp.njlS8oR0sf/.cml/cml-ehsjbxeja3/_work/cml-pulse/cml-pulse/ci'`

and:
```yml
...
  test:
    needs: [setup]
    runs-on: [self-hosted, test]
    steps:           
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: |
          which cml
          cml ci
```
[Fails](https://github.com/dacbd/cml-pulse/runs/5607817035?check_suite_focus=true) with a `EEXIST: file already exists, symlink '../lib/node_modules/@dvcorg/cml/bin/cml.js' -> '/usr/bin/cml'`

----
However using `--cml-version=github:iterative/cml.git#master \` to trigger the `npm install -g` way of setting up cml on the runner instance works fine.

**Comment by dacbd** [comment]
~~Maybe there is a strange interaction with `pkg` and this:~~
https://github.com/iterative/cml/blob/f3406ac28cb98aeef5cc47f4754b4c8cac428b14/bin/cml.js#L35-L37
?

it appears that if `PKG_EXECPATH` set then it fails

**Comment by dacbd** [comment]
I think there is some strange process magic happening between:
- https://github.com/iterative/cml/blob/f3406ac28cb98aeef5cc47f4754b4c8cac428b14/bin/cml.js#L37
- https://github.com/0x2b3bfa0/node-pseudoexec/blob/main/index.js
- https://github.com/vercel/pkg/blob/85ccec331bd81dcbc49916ba9862955e0e053ec6/lib/fabricator.ts#L67-L74

Im not sure what is setting that env var for the runner instance, you can see [here](https://github.com/dacbd/cml-pulse/runs/5608747367?check_suite_focus=true) (**_the key there has been revoked_**)




Bad
```
FROM debian:buster

RUN apt-get update && apt-get install -y curl
RUN mkdir -p /opt/cml/
RUN curl --location --url https://github.com/iterative/cml/releases/download/v0.12.0/cml-linux --output /opt/cml/cml-linux
RUN chmod +x /opt/cml/cml-linux
ENV PKG_EXECPATH=/opt/cml/cml-linux
RUN ln -s /opt/cml/cml-linux /usr/bin/cml
```

Good
```
FROM debian:buster

RUN apt-get update && apt-get install -y curl
RUN mkdir -p /opt/cml/
RUN curl --location --url https://github.com/iterative/cml/releases/download/v0.12.0/cml-linux --output /opt/cml/cml-linux
RUN chmod +x /opt/cml/cml-linux
RUN ln -s /opt/cml/cml-linux /usr/bin/cml

```

**Comment by dacbd** [comment]
Actually, it looks like this might be the culprit in `which` https://github.com/npm/node-which/blob/main/which.js#L21 

_because_

https://github.com/vercel/pkg#snapshot-filesystem 

> On the other hand, in order to access real file system at run time (pick up a user's external javascript plugin, json configuration or even get a list of user's directory) you should take process.cwd() or path.dirname(process.execPath).

**Comment by 0x2b3bfa0** [comment]
All the mentions to [`node-pseudoexec`](https://github.com/0x2b3bfa0/node-pseudoexec) are, at least, libellous. 😄 Fortunately, this error doesn't seem to have anything to do with the command plugin feature from #703.

When you (1) run `cml runner --cloud=gcp` it creates a cloud instance and (2) runs `cml runner` inside, which, in turn, (3) executes the [GitHub Actions runner](https://github.com/actions/runner) in charge of (4) running the workflow that (5) calls `cml ci` in the example above.

The `cml` standalone binary (#842 & https://github.com/iterative/terraform-provider-iterative/pull/255) used for (2) is a [`pkg`](https://github.com/vercel/pkg) binary. As such, it sets the `PKG_EXECPATH` environment variable that propagates to all the child processes up to (5).

I don't understand yet why setting `PKG_EXECPATH` causes binaries bundled with `pkg` to fail, but this can be mitigated by unsetting this variable before calling the GitHub runner process; see #802 for a stale draft.

**Comment by dacbd** [comment]
> libelous

🤣 /edit that was the one strikethrough I missed, I have not revisited the rabbit hole I dug trying to find the root of the issue

> The `cml` standalone binary (#842 & [iterative/terraform-provider-iterative#255](https://github.com/iterative/terraform-provider-iterative/pull/255)) used for (2) is a [`pkg`](https://github.com/vercel/pkg) binary. As such, it sets the `PKG_EXECPATH` environment variable that propagates to all the child processes up to (5).
>
Does it set the env? In my basic docker reproduction running a `cml` command did not seem to set that ENV? .... Though...
 
> I don't understand yet why setting `PKG_EXECPATH` causes binaries bundled with `pkg` to fail, but this can be mitigated by unsetting this variable before calling the GitHub runner process; see #802 for a stale draft.

I suspect you are correct that #802 would fix this.

**Comment by 0x2b3bfa0** [comment]
> _Does it set the env? In my basic docker reproduction running a cml command did not seem to set that ENV?_

Yes, it does:

```yml
test:
  needs: [setup]
  runs-on: [self-hosted, test]
  steps:           
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - run: |
        env | grep PKG_EXECPATH
```
