### ISSUE TITLE
cml send-github-check hangs and does not report

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/cml#941]
I've been playing with `cml ci` and `cml send-github-check` [here](https://github.com/MantisAI/Rasa-MLOPs/pull/11). Not sure if my expectation is connect, but I was expecting `send-github-check` to:

1. post a comment like `cml send-comment`
2. Return a check success

Instead it seems to hangs with `CML Report Expected — Waiting for status to be reported`.

**Comment by 0x2b3bfa0** [comment]
Unable to reproduce

```yaml
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - run: cml send-github-check <(date)
        env:
          GITHUB_TOKEN: ${{ github.token }}

```
---
![Captura de pantalla 2022-05-10 a las 15 41 45](https://user-images.githubusercontent.com/11387611/167642588-58ab7d04-39f8-41e4-bcc7-13d59bbe9b02.png)
---
![Captura de pantalla 2022-05-10 a las 15 42 05](https://user-images.githubusercontent.com/11387611/167642601-45280c1d-9a96-4607-b5b7-a652fea4c07b.png)
