### ISSUE TITLE
newline after .md table?

### ISSUE THREAD

**Issue by elleobrien** [iterative/cml#95]
I have a workflow that publishes a report with a `dvc diff` table, then an image. It looks like the image is getting added as part of the table. Is there maybe a newline character missing in the output generated by `cml-metrics`?

![Screen Shot 2020-05-13 at 2 56 14 PM](https://user-images.githubusercontent.com/29716724/81870380-8e7dde00-952a-11ea-8420-c10952f20ac3.png)

```yaml
name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip3 install -r requirements.txt
          
          # Pull dataset with DVC 
          dvc pull
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro train.dvc
          
          # Use DVC metrics diff to compare metrics to previous commit
          BASELINE=origin/master
          dvc metrics diff --show-json "$BASELINE" | cml-metrics >> report.md
          
          # Add figure to report
          cml-publish pr_curve.png --md --title 'pr curve' >> report.md
          cml-send-github-check report.md 
```
