### ISSUE TITLE
`cml ci` fails within container

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#971]
minimal example:
```yml
name: test cml ci
on:
  push:
  workflow_dispatch:

jobs:
  test-v2:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v2
      - run: cml ci
  test-v3:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v3
      - run: cml ci
  test-setup-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - run: cml ci
  test-setup-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - run: cml ci
```
https://github.com/dacbd/err/actions/runs/2182120620

test-v2 / test-v3 fail with an error:
```
{
  "level": "error",
  "message": "Command failed: git config --get remote.origin.url",
  "output": [
    null,
    {
      "data": [],
      "type": "Buffer"
    },
    {
      "data": [],
      "type": "Buffer"
    }
  ],
  "pid": 126,
  "signal": null,
  "stack": "Error: Command failed: git config --get remote.origin.url\n    at checkExecSyncError (node:child_process:828:11)\n    at execSync (node:child_process:902:15)\n    at gitRemoteUrl (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:29:15)\n    at new CML (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:76:44)\n    at Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/ci.js:10:15)\n    at /usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:9054\n    at j (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4931)\n    at M.applyMiddlewareAndGetResult (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:9023)\n    at M.runCommand (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:7206)\n    at Xt.[runYargsParserAndExecuteCommands] (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:57164)\n    at Xt.parse (/usr/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:39275)\n    at Object.<anonymous> (/usr/lib/node_modules/@dvcorg/cml/bin/cml.js:90:4)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
  "status": 1,
  "stderr": {
    "data": [],
    "type": "Buffer"
  },
  "stdout": {
    "data": [],
    "type": "Buffer"
  }
}
```
 when I expect them to complain with same `token not found` as the test-setup-v2/v3
