### ISSUE TITLE
`src/pipe-args.js` hangs when `cml` is called from `child_process.exec` on macOS

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#982]
The cursed `pipe-args.js` file is, **again**[^1] producing esoteric issues on kernels other than Linux: now it hangs forever on macOS when using [`child_process.exec`](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback) to run `cml --version` on https://github.com/iterative/setup-cml/pull/60. 🐇🕳️

```console
$ npm install --global @dvcorg/cml@0.15.1
$ node -e "require('child_process').exec('cml --version', console.log)"
```

https://github.com/iterative/cml/blob/25747f67d6d3b7d36158032075366cda07919271/bin/cml.js#L85

https://github.com/iterative/cml/blob/25747f67d6d3b7d36158032075366cda07919271/bin/cml/publish.js#L8

https://github.com/iterative/cml/blob/25747f67d6d3b7d36158032075366cda07919271/src/pipe-args.js#L21

https://github.com/iterative/cml/blob/25747f67d6d3b7d36158032075366cda07919271/src/pipe-args.js#L28-L30

Calling [`fs.readSync`](https://nodejs.org/api/fs.html#fsreadsyncfd-buffer-offset-length-position) throws [`EAGAIN`](https://nodejs.org/api/os.html#os_posix_error_constants) when there is no data in the standard input, causing an infinite loop in macOS. A similar bug affects Windows, where reading from standard input with no data just hangs `readSync` forever.

[^1]: https://github.com/iterative/cml/pull/732#issue-1004203281

**Comment by 0x2b3bfa0** [comment]
### Minimal example

```yaml
on: workflow_dispatch
jobs:
  example:
    runs-on: macos-latest
    steps:
    - run: >-
        node -e
        'require("child_process").execFile("node", ["-e", process.argv[1]], console.log)'
        'require("fs").readSync(0, Buffer.alloc(1))'
```
